# Generated by Django 4.0.8 on 2022-12-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField(editable=False, help_text='The access token granted by the Discord SSO.')),
                ('ttl', models.PositiveIntegerField(editable=False, help_text='The number of seconds that the token is valid for.')),
                ('refresh_token', models.TextField(editable=False, help_text='A re-usuable token used to generate a new access token once they expire.', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user that the token belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
