# Generated by Django 4.0.8 on 2022-12-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0002_scope_alter_token_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='scopes',
            field=models.ManyToManyField(help_text='The scopes granted to this token', to='discord_auth.scope'),
        ),
    ]
