# Generated by Django 4.0.8 on 2022-12-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0004_alter_token_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='discord_user_id',
            field=models.CharField(db_index=True, default='aaaa', help_text='The discord user id for which this token is valid.', max_length=255),
            preserve_default=False,
        ),
    ]
