# Generated by Django 4.0.8 on 2023-01-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord_auth', '0005_token_discord_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordCallbackRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Session key identifying the session this redirect was created for.', max_length=254, unique=True)),
                ('url', models.TextField(default='/', help_text='The internal URL to redirect this callback to')),
                ('state', models.CharField(help_text='OAuth2 state string to represent this session.', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(blank=True, help_text='Token generated by a complete code exchange from callback processing.', null=True, on_delete=django.db.models.deletion.CASCADE, to='discord_auth.token')),
            ],
        ),
    ]
