# Generated by Django 4.0.8 on 2023-01-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discord_user_id',
            field=models.CharField(db_index=True, help_text='The discord user id for which this token is valid.', max_length=255, null=True),
        ),
    ]
