# Generated by Django 4.0.8 on 2023-01-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_discord_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discord_avatar_hash',
            field=models.CharField(help_text='The avatar hash for the discord user.', max_length=255, null=True),
        ),
    ]
